name: Pre-merge

run-name: pre-merge-to-main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Emit JS
    runs-on:
      - ubuntu-latest
      # - windows-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      
      - name: Setup Node LTS
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Build project
        run: pnpm run build